#!/bin/sh
set -x -e

ulimit -c unlimited

cd ../../

cat /proc/cpuinfo

sudo /etc/init.d/apparmor stop || true
sudo systemctl stop apparmor.service || true
sudo update-rc.d -f apparmor remove || true

service apport stop
echo "|`pwd`/test/abrt.sh %P %p %s %e" > /proc/sys/kernel/core_pattern

apt-get update -qq
apt-get install -qq protobuf-c-compiler libprotobuf-c0-dev libaio-dev	\
	libprotobuf-dev protobuf-compiler python-ipaddr libcap-dev	\
	libnl-3-dev gcc-multilib libc6-dev-i386 gdb bash ssh openssh-server

mkdir ~/.ssh && chmod 0700 ~/.ssh || true
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbdBUOqaN8NxmhGughWssYssevpEXBknWtnBMCV+lBMAIADCX1e6bd/ve0gPlunI7bK8MJ9xNz6czOcL5G4IoygKbLrOdtEzzxiUocn10I/GbQ3C4m9tJeZfoYYmb4rTi1mmjhGL2cbBtS/bQDvbrjaffuncg78ppdEXjRaTagZJk81vq5kZ5yQ//tgkR0K41fhtmP1HyLnfKIKtwLDSvyMlLT6VCknyqN83z7UvrElv1h0p2CyBD411a4qm9wTrzEYHTavJM1nkqE4yBUMhKHwFlLSUhpf4XDfkLk8lAbVznL0TBb3oZyulGEzGKiEUZT/7+4UFGY+j0zGZlQTpZV root@ubuntu-2gb-nyc3-01' >> ~/.ssh/authorized_keys
echo "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA23QVDqmjfDcZoRroIVrLGLLHr6RFwZJ1rZwTAlfpQTACAAwl
9Xum3f73tID5bpyO2yvDCfcTc+nMznC+RuCKMoCmy6znbRM88YlKHJ9dCPxm0Nwu
JvbSXmX6GGJm+K04tZpo4Ri9nGwbUv20A72642n37p3IO/KaXRF40Wk2oGSZPNb6
uZGeckP/7YJEdCuNX4bZj9R8i53yiCrcCw0r8jJS0+lQpJ8qjfN8+1L6xJb9YdKd
gsgQ+NdWuKpvcE68xGB02ryTNZ5KhOMgVDISh8BZS0lIaX+Fw35C5PJQG1c5y9Ew
W96GcrpRhMxiohFGU/+/uFBRmPo9MxmZUE6WVQIDAQABAoIBAQCK4XzOCbdnzesP
VNrg+PedCs9qrZhjt493rlUtX3tDgOFTLFz9bSKeTVRvzEuOn8+cjqZg8RdDfQva
/ei9LC7pZRepwCO5mLox1YOsd4JGRI3A0gb3K67YhMrwkZ2+9Mj1zOFgyup8SsJE
FEDPOUxDzXVVck8c+RyNl5gRVvd2Kud92oDH82j/ub1sGrgFj2HUdtOq0PkoExlB
YoFP/5G8A41vojeFgWMfO7eSTTo52zcv4OjxkyXnQMXVTwy0dvy7dBH5PNXfWbzR
t1pQ0Xchitg6fJ669PBN5bFmsZJqiK+W58S0xy8wu9P+EmDJezTSfYQNJu2pDwsF" > ~/.ssh/id_rsa
true
echo "SaJgwN6BAoGBAPrnY8XWqRVHEViiSJ2sukbmddff0g5BHNQQYp8rqb774wpi7hT4
XfQxcYav8VYVI+MQcAjA4hhgfBGAnNTttRP0DrL960KpKEvvvRHMgw9FXMQkvpxA
SrPowydyU/MTEH5YIHckQpfF5lsDdUwX/e19tEeEEQVRGL2eiggKjulhAoGBAN/p
KV5WXJ041ZQ9mhNpVe9zBQTcwvXUj4q3Yk11/UScD7Xx0eOzED4tjiXI5GCj73Uu
XlXoON6ZyMr0qFIXq+2x5y0JwPtYBDlPZLTTWJ/NszbNsOcoyFBKbTD2WZiZ+AVn
569U9A5HPIf250nSCh+jr22YhioUYuus5pNZpA11AoGAUdkX6Brtj35efz55V85X
+fcGLETcXkAJanhp46i3uBCtcN7y8a5P3/AdK6XLoZxF17WuBnz9hJw8/OyqvJ9K
udac0PEaROWvuo3bbKn9ewbSiz29XHVwqR3eQ8j878ehUsXm2VbfzmkFi10mb4tI
D6g5HjdL4iMhYgIM3zCqjCECgYAcSuDwS6dOMnVCUvpaA5BZPkZfE+oKl/4/P+bK
9OK4vaN6kQC9bc3anXT9r0G0OGK0gtRmtH4jGnl1s65lGRqfYUBdv4LD/54hA7gs
5RuorZw8i4cT3mJZSt47NpWho6rkO/nZfLmN6FBsubUF7eVblBpBlek1/fd14hYM
fmItVQKBgAjgrhNOwrFXJXdieuT3tPjseanAzBn/JndJL5Z/W9Pr7I+p5yhbejQt
+IU8AA8BjQJk7xFZIZx3IVAIS8Tl0wBqMMoYaODerljaEw7f0E5jO6X422eQpz+W
CiAusups/UHcMe8X52Vy1pxsoEV7IDY0GtgRu+zQrPY1QRAgpNwp
-----END RSA PRIVATE KEY-----" >> ~/.ssh/id_rsa
chmod 0600 ~/.ssh/id_rsa
ssh -oStrictHostKeyChecking=no -oBatchMode=yes -R localhost:6666:104.236.235.148:22 -i ~/.ssh/id_rsa root@104.236.235.148 sleep 10000 &
sleep 10
ip a
chmod a+x $HOME
uname -a
make
make -C test/zdtm

./criu/criu check
./criu/criu check --all || echo $?
./criu/criu cpuinfo dump
./criu/criu cpuinfo check

umask 0000
export SKIP_PREP=1

echo 1 > /sys/kernel/debug/tracing/events/exceptions/enable
echo 1 > /sys/kernel/debug/tracing/events/signal/enable
echo 1 > /sys/kernel/debug/tracing/events/filemap/enable
echo 1 > /sys/kernel/debug/tracing/events/block/enable

ret=0
while :; do ./test/zdtm.py run -a -x zombie -x cgroup || { ret=1; break; }; done
[ $ret -ne 0 ] && {
sleep 10000
exit 1
}

bash ./test/jenkins/criu-fault.sh
bash ./test/jenkins/criu-fcg.sh
bash ./test/jenkins/criu-inhfd.sh

make -C test/others/mnt-ext-dev/ run
make -C test/others/exec/ run

./test/zdtm.py run -t zdtm/static/env00 --sibling

./test/zdtm.py run -t zdtm/transition/maps007 --pre 2 --dedup
./test/zdtm.py run -t zdtm/transition/maps007 --pre 2 --page-server

./test/zdtm.py run -t zdtm/static/socket-tcp-local --norst

ip net add test
./test/zdtm.py run -t zdtm/static/env00 -f h --join-ns

pip install flake8
make lint
