#!/bin/sh
set -x -e

cd ../../

sudo chown -R travis .

# We only need to run the below for gcov-enabled builds
test -z "$GCOV" && exit 0

find -name '*.gcno' > gcno-list
tar -c --files-from=gcno-list | tar -x -C test/zdtm/static/chroot.dir.test/`pwd`/
tar -c --files-from=gcno-list | tar -x -C test/zdtm/static/chroot-file.dir.test/`pwd`/

sudo apt-get install -qq -y lcov
gem install -V --no-user-install coveralls-lcov
lcov --directory . --capture --output-file coverage.info
coveralls-lcov coverage.info
