#!/bin/sh
set -x -e

# We only need to run the below for gcov-enabled builds
test -z "$GCOV" && exit 0

cd ../../

sudo apt-get install -qq -y lcov
gem install -V --no-user-install coveralls-lcov
lcov --directory . --capture --output-file coverage.info --ignore-errors graph
coveralls-lcov coverage.info
