#!/bin/sh
set -x -e

TRAVIS_PKGS="protobuf-c-compiler libprotobuf-c0-dev libaio-dev
		libprotobuf-dev protobuf-compiler python-ipaddr libcap-dev
		libnl-3-dev gdb bash python-protobuf python-protobuf kexec-tools"

travis_prep () {
	[ -n "$SKIP_TRAVIS_PREP" ] && return

	cd ../../

	service apport stop

	apt-get update -qq
	apt-get install -qq $TRAVIS_PKGS
		if [ "$CLANG" = "1" ]; then
			apt-get install -qq clang
			MAKE_VARS=CC=clang
		fi
	chmod a+x $HOME
}

travis_prep

ulimit -c unlimited
echo "|`pwd`/test/abrt.sh %P %p %s %e" > /proc/sys/kernel/core_pattern

export GCOV
make ${MAKE_VARS}

cd ../../
./scripts/travis/kexec.sh
